### ISSUE TITLE
[lang-model]: First-class tuple-destructuring within `Expr::Lambda` argument capture (`moderate`, `common`, `sem`)

### ISSUE THREAD

**Issue by archaephyrryx** [yeslogic/doodle#208]
We currently have a very simple model of lambda abstractions within the `Expr` layer, and to a far lesser extent, the fused lambdas used by `Format` in primitives such as `ForEach`:

```rust
pub enum Expr {
    Lambda(Label, Box<Expr>)
}
```

Because `Expr::Lambda` is constrained by the type-system within the model to appear only in specific parameters of specific higher-order `Expr` primitives such as `FlatMapAccum`, those sites constitute the overwhelming majority of cases we are likely to apply it to. Therefore, any patterns of usage implicated by those sites, has a significant impact on what sort of lambdas we are prone to producing within a Format definition.

In particular, we have, even just currently, two common sites where the head of a lambda is explicitly understood to be a pair of individual values, which are more often than not used completely independently within the lambda body rather than evaluated together under a single operation. These sites in question, being `Expr::FlatMapAccum` and `Expr::FlatMapList`, which respectively take `(Accum, Element)` of either, in the former case, a specified but unconstrained type for `Accum`, or in the latter case, a Sequence over a specified element-type.

What often ends up happening in these cases is that we grant the head of the tuple a name indicating its nature as a pair of values, and then perform individual tuple-projections using `tuple_proj` to access its two elements independently. This pattern not only means we are unable to bind the the two variables independently in our model, but also carries over into the code we generate, where the lack of a pattern for named tuple-destructuring means we inevitably have single-argument closures that might normally be written out, if we were doing so by hand, as a destructured pair.

It isn't quite clear how much work it would be to fully implement support for double-barrel lambdas in our current model, but it would be a decent reduction in cognitive load when writing out such lambdas, and produce clearer output in the post-code-generation layer.

Note that this issue only covers the proposal of Tuple-destructuring bindings specifically, and does not extend to:
   - Sequence destructuring, which is fallible
   - Record destructuring, which is not possible without a Struct expression in any case and is far less baked-in to the Expr model
   - Enum-based destructuring, which is fallible
  
We are also not specifically proposing that we extend support to *all* possible tuple-arities, though it might be easier to implement generically for any tuple-arity than to artificially restrict to a small set of sizes. At most, we would propose at least up to 8-tuples, as that is the basic requirement of the `Format::Map` lambda used to define the BaseModule-formats `U64Be/U64Le`.

**Comment by mikeday** [comment]
So is this describing a separate feature distinct from "lambdas that take two arguments" and don't involve a tuple at all?

**Comment by archaephyrryx** [comment]
That is one of two approaches, perhaps. Arguably the only reason we passed around tuples in the first place was to get around having to curry things with nested single-argument lambdas, or allow for multi-argument lambdas at any layer. So that would be an equivalent fix, though this is perhaps slightly easier to express as a problem. And then, even if we *did* have multi-argument lambdas, we might still want this feature.

**Comment by mikeday** [comment]
So how would you describe this other feature, exactly? How does it differ from a tuple pattern match?

**Comment by archaephyrryx** [comment]
Not much different, in point of fact. If we had the ability to specify a selected subset of Pattern that were allowed in the head position of a Lambda, that might be the ideal.

For instance, if we didn't have a concept of Pattern to go off of or try to re-use, this is more or less what we might want to define for Lambdas:

```rust
pub enum LambdaPattern {
    BindWildcard,
    BindVariable(Label),
    TupleDestruct(Vec<LambdaPattern>),
}
```

Or something like that.

**Comment by archaephyrryx** [comment]
I guess we could approxmate the ideal behavior using an adapter/helper:

```rust
fn lambda_tuple<const N: usize>(names: [&'static str; N], body: Expr) -> Expr {
    lambda("tuple_var", expr_match(var("tuple_var"), [(Pattern::Tuple(names.into_iter().map(Label::from).collect()), body)])
}
```

**Comment by archaephyrryx** [comment]
Closing for now, as we have #209 merged.
